### ISSUE TITLE
base url in XAMPP/Laragon/etc

### ISSUE THREAD

**Issue by zahovicS** [leafsphp/http#13]
I have a problem, I am using laragon as local server, when I want to do the redirection
return response()->redirect("/home");
the url to which it redirects me is 
**http://localhost/home**
it should redirect me to 
**http://localhost/leaf-test/home**

**Comment by mychidarko** [comment]
Hi @zahovicS, I'll check this out.

**Comment by milosPavic** [comment]
I use code igniter, but how your server is set for my coding perspective he does you right.
So when you server any site /is root and /home is on proper place http://localhost/home
so your server if it is start / is http://localhost/leaf-test but points to http://localhost/ if you use  proper server
ELSE ruting rules wont work
thats why your app root http://localhost/leaf-test is always on server root http://localhost/
in code igniter it is example
http://localhost:4567/
so that you can run multiple servers on different ports

**Comment by fadrian06** [comment]
I've the same problem, to partially solve it I had to create some `Path` module with a `base() static method`, that removes `/index.php` from `$_SERVER['PHP_SELF']`, so then always uses `localhost/`
or `localhost/my-project`...

That works for me, but I'd like that leaf could solve this problem

**Comment by mychidarko** [comment]
About this issue, I forgot to ask if you tried setting a base app url

https://leafphp.dev/docs/routing/sub-folder.html

This should actually solve your issue

**Comment by zahovicS** [comment]
@mychidarko 
Yes, I tried it but still the redirects always went to "/" and not to "/leaf-test"
I had to create a method as a previous user said, where I put the complete url taken from the .ENV
I don't know if I mentioned it but I'm using Leaf MVC.
Even if it's a temporary solution, I love the whole Leaf project :)

**Comment by mychidarko** [comment]
This has been fixed. A new version will be published soon 🚀
